language: python
cache: pip
python:
  - 2.7
  - 3.6
  - 3.7
install:
  - pip install tox-travis coveralls
script: tox
after_success: coveralls
notifications:
  email:
    on_success: never
    on_failure: always